#Config by Aleondev
# Version 1
# "§"
# "\n"
# Hir kannst du die message ändern.

#GM1.

gm1: "§eCore§b>>Gm1"

#GM0.

gm0: "§eCore§b>>Gm0"

#GM3.

gm3: "§eCore§b>>Gm3"

#GM2

gm2: "§eCore§b>>Gm2"

#Join Message.

join: "§a[+]"

#Quit Message.

quit: "§c[-]"

#Tag.

tag: "§eCore§b>>Tag"

#Nacht.

nacht: "§eCore§b>>Nacht"

#Flyon.

flyon: "§eCore§b>>Flyon"

#Flyoff.

flyoff: "§eCore§b>>Flyoff
